services:
  wiremock:
    image: "wiremock/wiremock:3.10.0"
    container_name: my_wiremock
    ports:
      - "8443:8443"
      - "8080:8080"
    volumes:
      - ./mocks/__files:/home/wiremock/__files
      - ./mocks/mappings:/home/wiremock/mappings
    entrypoint: [ "/docker-entrypoint.sh",  "--disable-gzip", "--https-port=8443", "http-port=8080", "--record-mappings", "--enable-stub-cors", "--verbose" ]